import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, CircleEllipsis } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { bookings } from "@/lib/booking-data";

export const Route=createFileRoute("/bookings")({head:()=>({meta:[{title:"My bookings — VERA HOLIDAYS"},{name:"description",content:"View and manage your VERA HOLIDAYS bookings."},{property:"og:title",content:"My bookings — VERA HOLIDAYS"},{property:"og:description",content:"View upcoming and past travel plans."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BookingsPage});
const statusStyle:Record<string,string>={confirmed:"bg-success/15 text-success",pending:"bg-info/15 text-info",cancelled:"bg-secondary text-muted-foreground","partially confirmed":"bg-warning/15 text-warning"};
function BookingsPage(){const [cancelled,setCancelled]=useState<string[]>([]);return <AppShell><main className="mx-auto max-w-5xl px-5 py-12"><p className="text-sm font-semibold text-primary">YOUR TRIPS</p><h1 className="mt-2 text-3xl font-bold">My bookings</h1><div className="mt-9 space-y-4">{bookings.map(b=>{const status=cancelled.includes(b.ref)?"cancelled":b.status;return <article key={b.ref} className="flex flex-col gap-5 rounded-2xl border border-border p-6 sm:flex-row sm:items-center"><div className="grid size-14 shrink-0 place-items-center rounded-xl bg-brand-soft text-primary"><CalendarDays/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{b.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${statusStyle[status]}`}>{status}</span></div><p className="mt-1 text-sm text-muted-foreground">{b.dates} · Ref {b.ref}</p></div><div className="sm:text-right"><p className="font-semibold">{b.amount}</p>{b.upcoming&&status!=="cancelled"&&<AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="sm" className="mt-2 text-muted-foreground"><CircleEllipsis/>Cancel booking</Button></AlertDialogTrigger><AlertDialogContent className="rounded-2xl"><AlertDialogHeader><AlertDialogTitle>Cancel this booking?</AlertDialogTitle><AlertDialogDescription>You’ll receive a refund of <strong className="text-foreground">{b.refund}</strong> to your original payment method. This usually takes 5–7 working days.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep booking</AlertDialogCancel><AlertDialogAction onClick={()=>setCancelled(v=>[...v,b.ref])}>Confirm cancellation</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div></article>})}</div></main></AppShell>}