import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, Plane, SlidersHorizontal, Star } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { flights, hotels, money } from "@/lib/booking-data";

export const Route = createFileRoute("/search")({
  head: () => ({ meta: [{ title: "Jaipur stays — VERA HOLIDAYS" }, { name: "description", content: "Compare thoughtful stays and flights for your trip." }, { property: "og:title", content: "Search results — VERA HOLIDAYS" }, { property: "og:description", content: "Compare thoughtful stays and flights for your trip." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: SearchPage,
});

function SearchPage() {
  const [type, setType] = useState<"hotels" | "flights">("hotels");
  const [amenity, setAmenity] = useState("Breakfast");
  return <AppShell><main className="mx-auto max-w-7xl px-5 py-10">
    <Link to="/" className="mb-7 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Back to search</Link>
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-primary">12–15 OCT · 2 GUESTS</p><h1 className="mt-2 text-3xl font-bold">Great options in Jaipur</h1><p className="mt-2 text-muted-foreground">{type === "hotels" ? "18 stays" : "12 flights"} match your trip</p></div><div className="flex rounded-full bg-secondary p-1"><Button variant={type==="hotels"?"default":"ghost"} className="rounded-full" onClick={()=>setType("hotels")}>Hotels</Button><Button variant={type==="flights"?"default":"ghost"} className="rounded-full" onClick={()=>setType("flights")}>Flights</Button></div></div>
    <div className="mt-10 grid gap-8 lg:grid-cols-[240px_1fr]">
      <aside className="h-fit rounded-2xl border border-border p-5"><h2 className="flex items-center gap-2 font-semibold"><SlidersHorizontal className="size-4"/>Filters</h2><div className="mt-6"><label className="text-sm font-medium">Price per night</label><input type="range" min="1500" max="12000" defaultValue="7500" className="mt-3 w-full accent-primary"/><div className="flex justify-between text-xs text-muted-foreground"><span>₹1,500</span><span>₹12,000+</span></div></div><div className="mt-7"><p className="text-sm font-medium">Rating</p><div className="mt-3 flex gap-2">{[3,4,5].map(n=><Button key={n} size="sm" variant="outline" className="rounded-full">{n}<Star className="size-3"/></Button>)}</div></div><div className="mt-7"><p className="text-sm font-medium">Amenities</p><div className="mt-3 flex flex-wrap gap-2">{["Breakfast","Pool","Wi-Fi"].map(item=><Button key={item} size="sm" variant={amenity===item?"default":"outline"} className="rounded-full" onClick={()=>setAmenity(item)}>{amenity===item&&<Check/>}{item}</Button>)}</div></div></aside>
      <section className="space-y-4">{type === "hotels" ? hotels.map(({id,name,area,rating,reviews,price,rooms,icon:Icon,amenities})=><article key={id} className="grid gap-5 rounded-2xl border border-border p-5 transition-shadow hover:shadow-soft sm:grid-cols-[150px_1fr_auto]"><div className="grid min-h-36 place-items-center rounded-xl bg-brand-soft text-primary"><Icon className="size-12"/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{name}</h2>{rooms<=2&&<span className="rounded-full bg-warning/15 px-2.5 py-1 text-xs font-semibold text-warning">Only {rooms} room{rooms>1?"s":""} left</span>}</div><p className="mt-1 text-sm text-muted-foreground">{area}</p><p className="mt-3 flex items-center gap-1 text-sm"><Star className="size-4 fill-current"/><strong>{rating}</strong><span className="text-muted-foreground">({reviews})</span></p><div className="mt-4 flex flex-wrap gap-2">{amenities.map(a=><span key={a} className="rounded-full bg-secondary px-2.5 py-1 text-xs text-muted-foreground">{a}</span>)}</div></div><div className="flex flex-row items-end justify-between sm:flex-col"><div className="text-right"><strong className="text-xl text-primary">{money(price)}</strong><p className="text-xs text-muted-foreground">per night</p></div><Button asChild><Link to="/hotel">View stay</Link></Button></div></article>) : flights.map(f=><article key={f.id} className="flex flex-col gap-5 rounded-2xl border border-border p-6 sm:flex-row sm:items-center"><div className="grid size-14 place-items-center rounded-xl bg-brand-soft text-primary"><Plane/></div><div className="flex-1"><p className="font-semibold">{f.airline} <span className="font-normal text-muted-foreground">{f.code}</span></p><p className="mt-2 text-xl font-semibold">{f.from} <span className="mx-2 text-muted-foreground">→</span> {f.to}</p><p className="text-sm text-muted-foreground">{f.time} · {f.note}</p></div><div className="text-right"><strong className="text-xl text-primary">{money(f.price)}</strong><Button className="mt-3 w-full" asChild><Link to="/hotel">Select</Link></Button></div></article>)}</section>
    </div>
  </main></AppShell>;
}